FROM node:16-alpine
WORKDIR /app

deps:
  COPY package.json tsconfig.json package-lock.json ./
  RUN npm install
  COPY src/ src/
  COPY public/ public/

test:
  FROM +deps
  RUN npm test --watchAll=false

build:
  FROM +deps
  RUN npm run build
  SAVE ARTIFACT build/

build-dev-image:
  FROM +deps
  ENTRYPOINT ["npm", "start"]
  SAVE IMAGE threed-press-frontend:dev-build

run-dev:
  LOCALLY
  RUN earthly +build-dev-image
  RUN docker-compose up



