FROM node:16-alpine
WORKDIR /app

deps:
  COPY package.json tsconfig.json tsconfig.build.json package-lock.json ./
  RUN npm install
  COPY src/ src/

test:
  FROM +deps
  RUN npm test --watchAll=false

build:
  FROM +deps
  RUN npm run build
  SAVE ARTIFACT build/

build-dev-image:
  FROM +deps
  ENTRYPOINT ["npm", "run", "start:dev"]
  SAVE IMAGE threed-press-backend:dev-build

run-dev:
  LOCALLY
  RUN earthly +build-dev-image
  RUN docker-compose up